# Generated by Django 4.0 on 2022-08-21 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('image', models.ImageField(null=True, upload_to='category', verbose_name='иконка')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='app_item.category')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='название')),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('stock', models.PositiveIntegerField(verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item/%Y/%m/%d', verbose_name='изображение')),
                ('is_available', models.BooleanField(default=False, verbose_name='в наличии')),
                ('limited_edition', models.BooleanField(default=False, verbose_name='ограниченный тираж')),
                ('reviews', models.SmallIntegerField(default=0, verbose_name='просмотры')),
                ('comments', models.SmallIntegerField(default=0, verbose_name='комментарии')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='дата обновления')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_item.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ['created'],
            },
        ),
    ]
