# Generated by Django 4.0 on 2022-08-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0002_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='limited_edition',
            field=models.BooleanField(default=False),
        ),
    ]
