# Generated by Django 4.0 on 2022-08-27 07:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_item', '0004_alter_itemview_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='дата изменения')),
                ('main_image', models.BooleanField(default=False, verbose_name='главное изображения')),
                ('image', models.ImageField(blank=True, default='static/img/default_flat.jpg', null=True, upload_to='gallery/%Y/%m/%d', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(blank=True, max_length=20, related_name='items', to='app_item.Tag', verbose_name='тег'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активный'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='название тега'),
        ),
        migrations.AlterField(
            model_name='itemview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 12, 46, 38, 335504)),
        ),
        migrations.AlterModelTable(
            name='tag',
            table='app_tag',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='дата обновления')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_comments', to='app_item.item', verbose_name='товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='auth.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'db_table': 'app_item_comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
