# Generated by Django 4.0 on 2022-08-27 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0005_image_alter_tag_options_item_tag_tag_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 12, 49, 33, 726192)),
        ),
    ]
