# Generated by Django 4.0 on 2022-08-27 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0007_rename_comment_text_comment_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 13, 13, 16, 169180)),
        ),
    ]
