# Generated by Django 4.0 on 2022-08-27 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0008_alter_itemview_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 13, 27, 14, 601521)),
        ),
    ]
