# Generated by Django 4.0 on 2022-08-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_item', '0011_remove_comment_user_comment_session_alter_item_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='session',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='auth.user', verbose_name='пользователь'),
            preserve_default=False,
        ),
    ]
