# Generated by Django 4.0 on 2022-08-30 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0012_remove_comment_session_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='app_item.item'),
            preserve_default=False,
        ),
    ]
