# Generated by Django 4.0 on 2022-09-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0019_alter_orderitem_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created'], 'verbose_name': 'заказ'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['item'], 'verbose_name': 'выбранный товар'},
        ),
    ]
