# Generated by Django 4.0 on 2022-09-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0023_alter_itemview_options_alter_cartitem_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
