# Generated by Django 4.0 on 2022-10-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0025_item_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.AddField(
            model_name='item',
            name='new_image',
            field=models.ImageField(blank=True, null=True, upload_to='new_image/%Y/%m/%d'),
        ),
    ]
