# Generated by Django 4.0 on 2022-10-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0026_remove_item_color_item_new_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Picture',
        ),
    ]
