# Generated by Django 4.0 on 2022-10-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0027_rename_image_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picture',
            new_name='Image',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('title',), 'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='new_image',
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('blue', 'blue'), ('magenta', 'magenta'), ('white', 'white'), ('black', 'black'), ('grey', 'grey')], max_length=10, null=True, verbose_name='цвет товара'),
        ),
    ]
