# Generated by Django 4.0 on 2022-10-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0030_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
