# Generated by Django 4.0 on 2022-10-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0032_remove_category_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=1, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='item/%Y/%m/%d', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
