# Generated by Django 4.0 on 2022-10-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0004_alter_cartitem_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['created'], 'verbose_name': 'корзина', 'verbose_name_plural': 'корзины'},
        ),
    ]
