# Generated by Django 4.0 on 2022-10-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_cart', '0005_alter_cart_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='ordered',
            new_name='is_paid',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='all_items', to='app_cart.CartItem', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='оплаченный'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='auth.user', verbose_name='покупатель'),
        ),
    ]
