# Generated by Django 4.0 on 2022-10-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0006_rename_ordered_cartitem_is_paid_alter_cart_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='цена товара'),
            preserve_default=False,
        ),
    ]
