# Generated by Django 4.0 on 2022-10-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0005_remove_order_cart'),
        ('app_cart', '0007_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app_order.order'),
            preserve_default=False,
        ),
    ]
