# Generated by Django 4.0 on 2022-10-14 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0005_remove_order_cart'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_cart', '0010_alter_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Общая сумма'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='статус оплаты'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_is_paid', to='app_order.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='количество товара'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_add_items', to='auth.user', verbose_name='покупатель'),
        ),
    ]
