# Generated by Django 4.0 on 2022-08-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0002_alter_category_options_alter_category_slug_and_more'),
        ('app_user', '0002_alter_profile_options_alter_profile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='review_items',
            field=models.ManyToManyField(related_name='items', to='app_item.Item'),
        ),
    ]
