# Generated by Django 4.0 on 2022-08-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0004_alter_itemview_created'),
        ('app_user', '0003_profile_date_joined_profile_review_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='review_items',
            field=models.ManyToManyField(null=True, related_name='items', to='app_item.Item'),
        ),
    ]
