# Generated by Django 4.0 on 2022-08-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_comment_alter_profile_review_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
