# Generated by Django 4.0 on 2022-08-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0010_alter_itemview_created'),
        ('app_user', '0005_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='review_items',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='app_item.Item'),
        ),
    ]
