# Generated by Django 4.0 on 2022-09-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0024_remove_cartitem_item_remove_cartitem_user_and_more'),
        ('app_user', '0008_alter_profile_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='review_items',
            field=models.ManyToManyField(blank=True, related_name='item_views', to='app_item.Item'),
        ),
    ]
