# Generated by Django 4.0 on 2022-10-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0010_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
