# Generated by Django 4.0 on 2022-10-06 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cart', '0004_alter_cartitem_item'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В обработке'), ('is_ready', 'Готов'), ('completed', 'Выполнен'), ('deactive', 'Отменен')], max_length=20)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('telephone', models.CharField(max_length=10)),
                ('delivery', models.CharField(choices=[('express', 'экспресс'), ('standart', 'обычная')], max_length=12)),
                ('pay_type', models.CharField(choices=[('my_card', 'Онлайн картой'), ('some_card', 'Онлайн со случайного чужого счета')], max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='дата обновления')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cart.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'заказ',
                'db_table': 'app_order',
                'ordering': ['created'],
            },
        ),
    ]
