# Generated by Django 4.0 on 2022-10-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0002_remove_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
