# Generated by Django 4.0 on 2022-10-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0002_remove_order_pay_type_order_error_order_pay_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='сумма заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=200, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=200, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('express', 'экспресс'), ('standard', 'обычная')], max_length=20, verbose_name='доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=250, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=250, verbose_name='имя получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('online', 'Онлайн картой'), ('someone', 'Онлайн со случайного чужого счета')], max_length=20, verbose_name='оплата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В обработке'), ('is_ready', 'Готов'), ('completed', 'Выполнен'), ('deactivated', 'Отменен')], max_length=20, verbose_name='статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='телефон'),
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
