# Generated by Django 4.0 on 2022-10-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0003_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='error',
            field=models.CharField(default='', max_length=20),
        ),
    ]
