# Generated by Django 4.0 on 2022-10-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0004_alter_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
